### ISSUE TITLE
Report Checklist - [Entity]

### ISSUE THREAD

**Issue by mmagnuson-github** [mmagnuson-github/qa_sop#1]
- [ ] Year is correct
- [ ] All the pictures have captions
- [ ] 10.1
  - [ ] Score matches the finding
