### ISSUE TITLE
Report Checklist - CSUDH

### ISSUE THREAD

**Issue by mmagnuson-github** [mmagnuson-github/qa_sop#2]
- [x] Year is correct
- [x] All the pictures have captions
- [x] 10.1
  - [ ] Score matches the finding
